apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-deployment
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: log-ping-vol
          persistentVolumeClaim:
            claimName: shared-claim
      containers:
      - name: ping-pong
        image: chenoc/ping-pong-app:v5
        volumeMounts:
        - name: log-ping-vol
          mountPath: /mnt/data
        imagePullPolicy: Always  
        ports:
        - containerPort: 8080

