apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-claim
  namespace: exercises
spec:
  storageClassName: the-shared-pv 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
