apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
      - name: cache-vol
        persistentVolumeClaim:
          claimName: cache-image
      containers:
      - name: todo-app
        image: chenoc/todo-app:v5
        volumeMounts:
        - name: cache-vol
          mountPath: /caching
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080

