apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
      - name: log-output
        image: chenoc/log-output-app:v8
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: PINGPONG_SERVICE_URL
          value: "http://ping-pong-svc:8080"

